- name: Install base packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: Install gcc compilation related
  yum:
    name: "{{ gcc }}"
  vars: 
    gcc:
    - devtoolset-9-gcc.x86_64
    - devtoolset-9-gcc-gdb-plugin.x86_64
    - devtoolset-9-gcc-gfortran.x86_64
    - devtoolset-9-gcc-plugin-devel.x86_64
    state: latest

- name: Install pexpect
  pip:
    name: pexpect
    state: latest

- name: Ensure group "redis" exists
  group:
    name: redis
    state: present

- name: Ensure the user "redis" exists
  user:
    name: redis
    group: redis

- name: Stop redis server
  systemd:
    name: "redis_{{ redis_port }}"
    state: stopped
  tags: shutdown
  when: whether_uninstall

- name: Remove existing redis directory
  file:
    path: "{{ basedir }}"
    state: absent
    remote_src: 'True'
  when: whether_uninstall